inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - spec/dummy/db/**/*
    - spec/dummy/bin/**/*

# Yes, we have Kind::Of::Very::Long::Class::Names
Metrics/ClassLength:
  Max: 170

# On an 11-inch screen this works perfectly fine.
# Metrics/LineLength:
#   Max: 150

# The trailing comma prevents brain cells from dying on copy-paste errors
Style/TrailingComma:
  Enabled: false

# I'm not that picky. An empty line can even increase readability
Style/EmptyLinesAroundBlockBody:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false

